version: '3.8'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-bot
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: <paste token here>
